# ======================================================================

# @author: Lucas Vieira <lcssvieira@gmail.com>

# @version: 1.0.0

#

# @description: Compose to start UserAP

# ======================================================================

version: '3.7'


services:
  
  api:
    build:
      context: .
    container_name: api
    ports:
      - 3000:3000
    environment:
      SERVER_PORT: 3000
      DB_URL: mongodb://mongo:27017/userAPI
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:4.0
    container_name: mongo
    ports:
      - 27017:27017
    restart: always